USE [master]
GO

/****** Object:  Database [ARQOSDE]    Script Date: 9/28/2018 5:31:35 PM ******/
CREATE DATABASE [ARQOSDE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ARQOSDE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ARQOSDE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ARQOSDE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ARQOSDE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ARQOSDE] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ARQOSDE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ARQOSDE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ARQOSDE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ARQOSDE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ARQOSDE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ARQOSDE] SET ARITHABORT OFF 
GO

ALTER DATABASE [ARQOSDE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ARQOSDE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ARQOSDE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ARQOSDE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ARQOSDE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ARQOSDE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ARQOSDE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ARQOSDE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ARQOSDE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ARQOSDE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ARQOSDE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ARQOSDE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ARQOSDE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ARQOSDE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ARQOSDE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ARQOSDE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ARQOSDE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ARQOSDE] SET RECOVERY FULL 
GO

ALTER DATABASE [ARQOSDE] SET  MULTI_USER 
GO

ALTER DATABASE [ARQOSDE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ARQOSDE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ARQOSDE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ARQOSDE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ARQOSDE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ARQOSDE] SET QUERY_STORE = OFF
GO

USE [ARQOSDE]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ARQOSDE] SET  READ_WRITE 
GO

